### ISSUE TITLE
Feature idea: Report back battery to backend/home assistant

### ISSUE THREAD

**Issue by marciogranzotto** [sibbl/hass-lovelace-kindle-4#6]
It would be useful to report back the battery status and charging status to the docker service. Then the service could update a Home Assistant sensor through MQTT or something like that.

Doing that it's possible to have the battery level on the Lovelace dashboard.

I can help with that if I can find some free time to do it.

**Comment by sibbl** [comment]
This sounds like a good idea which I already tried in my first React rendering project, see [its readme section](https://github.com/sibbl/hass-kindle-screensaver/#optional-battery-level-entity). To avoid battery draining, I've sent the battery level with each image request to the server, which then updated it in Home Assistant.

I personally decided against implementing it in the new structure due to the fact that my kindle is plugged in all the time. 

Mqtt actually sounds like a good approach which I've not tried yet. `wget` with a HTTP connection to Home Assistant might also be a solid solution. Having this logic directly on the Kindle would be pretty cool!

**Comment by sibbl** [comment]
Closing as this should've been resolved meanwhile: https://github.com/sibbl/hass-lovelace-kindle-screensaver#how-to-set-up-the-webhook
